all:
	cd lib && ${MAKE}
	cd jkOwnLib && ${MAKE}
	cd blat && $(MAKE)
#	cd gfClient && $(MAKE)
#	cd gfServer && $(MAKE)
#	cd hg/pslPretty && $(MAKE)
#	cd hg/pslReps && $(MAKE)
#	cd hg/pslSort && $(MAKE)
#	cd utils/nibFrag && $(MAKE)
#	cd utils/faToNib && $(MAKE)
#	cd utils/faToTwoBit && $(MAKE)
#	cd utils/twoBitToFa && $(MAKE)
#	cd utils/twoBitInfo && $(MAKE)
#	cd webBlat && $(MAKE)

clean:
	rm -f */*.o */*/*.o lib/*/*.a
