/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if you have the <ahocorasick/ahocorasick.h> header file. */
#define HAVE_AHOCORASICK_AHOCORASICK_H 1

/* Define to 1 if you have the <boost/icl/interval_set.hpp> header file. */
#define HAVE_BOOST_ICL_INTERVAL_SET_HPP 1

/* Define to 1 if you have the <bwa/bwa.h> header file. */
#define HAVE_BWA_BWA_H 1

/* clock_getttime found */
#define HAVE_CLOCK_GETTIME 1

/* Define to 1 if you have the <htslib/hts.h> header file. */
#define HAVE_HTSLIB_HTS_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Name of package */
#define PACKAGE "snowtools"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "jwala@broadinstitute.org"

/* Define to the full name of this package. */
#define PACKAGE_NAME "snowtools"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "snowtools 1.0"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "snowtools"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.0"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "1.0"
